package io.github.dravengarden.d1.jdbc

import java.sql.Array as SqlArray
import java.sql.Blob
import java.sql.CallableStatement
import java.sql.Clob
import java.sql.Connection
import java.sql.DatabaseMetaData
import java.sql.NClob
import java.sql.PreparedStatement
import java.sql.SQLFeatureNotSupportedException
import java.sql.SQLWarning
import java.sql.SQLXML
import java.sql.Savepoint
import java.sql.Statement
import java.sql.Struct
import java.util.Properties
import java.util.concurrent.Executor

private fun ni(name: String): Nothing =
    throw SQLFeatureNotSupportedException("d1: Connection.$name not supported")

public abstract class AbstractConnection : Connection {
    override fun createStatement(): Statement = ni("createStatement")

    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int): Statement =
        ni("createStatement")

    override fun createStatement(
        resultSetType: Int,
        resultSetConcurrency: Int,
        resultSetHoldability: Int,
    ): Statement = ni("createStatement")

    override fun prepareStatement(sql: String?): PreparedStatement = ni("prepareStatement")

    override fun prepareStatement(
        sql: String?,
        resultSetType: Int,
        resultSetConcurrency: Int,
    ): PreparedStatement = ni("prepareStatement")

    override fun prepareStatement(
        sql: String?,
        resultSetType: Int,
        resultSetConcurrency: Int,
        resultSetHoldability: Int,
    ): PreparedStatement = ni("prepareStatement")

    override fun prepareStatement(sql: String?, autoGeneratedKeys: Int): PreparedStatement =
        ni("prepareStatement")

    override fun prepareStatement(sql: String?, columnIndexes: IntArray?): PreparedStatement =
        ni("prepareStatement")

    override fun prepareStatement(sql: String?, columnNames: Array<String>?): PreparedStatement =
        ni("prepareStatement")

    override fun prepareCall(sql: String?): CallableStatement = ni("prepareCall")

    override fun prepareCall(
        sql: String?,
        resultSetType: Int,
        resultSetConcurrency: Int,
    ): CallableStatement = ni("prepareCall")

    override fun prepareCall(
        sql: String?,
        resultSetType: Int,
        resultSetConcurrency: Int,
        resultSetHoldability: Int,
    ): CallableStatement = ni("prepareCall")

    override fun nativeSQL(sql: String?): String = ni("nativeSQL")

    override fun setAutoCommit(autoCommit: Boolean): Unit = ni("setAutoCommit")

    override fun getAutoCommit(): Boolean = ni("getAutoCommit")

    override fun commit(): Unit = ni("commit")

    override fun rollback(): Unit = ni("rollback")

    override fun rollback(savepoint: Savepoint?): Unit = ni("rollback")

    override fun close(): Unit = ni("close")

    override fun isClosed(): Boolean = ni("isClosed")

    override fun getMetaData(): DatabaseMetaData = ni("getMetaData")

    override fun setReadOnly(readOnly: Boolean): Unit = ni("setReadOnly")

    override fun isReadOnly(): Boolean = ni("isReadOnly")

    override fun setCatalog(catalog: String?): Unit = ni("setCatalog")

    override fun getCatalog(): String? = ni("getCatalog")

    override fun setTransactionIsolation(level: Int): Unit = ni("setTransactionIsolation")

    override fun getTransactionIsolation(): Int = ni("getTransactionIsolation")

    override fun getWarnings(): SQLWarning? = ni("getWarnings")

    override fun clearWarnings(): Unit = ni("clearWarnings")

    override fun getTypeMap(): MutableMap<String, Class<*>> = ni("getTypeMap")

    override fun setTypeMap(map: MutableMap<String, Class<*>>?): Unit = ni("setTypeMap")

    override fun setHoldability(holdability: Int): Unit = ni("setHoldability")

    override fun getHoldability(): Int = ni("getHoldability")

    override fun setSavepoint(): Savepoint = ni("setSavepoint")

    override fun setSavepoint(name: String?): Savepoint = ni("setSavepoint")

    override fun releaseSavepoint(savepoint: Savepoint?): Unit = ni("releaseSavepoint")

    override fun createClob(): Clob = ni("createClob")

    override fun createBlob(): Blob = ni("createBlob")

    override fun createNClob(): NClob = ni("createNClob")

    override fun createSQLXML(): SQLXML = ni("createSQLXML")

    override fun isValid(timeout: Int): Boolean = ni("isValid")

    override fun setClientInfo(name: String?, value: String?): Unit = ni("setClientInfo")

    override fun setClientInfo(properties: Properties?): Unit = ni("setClientInfo")

    override fun getClientInfo(name: String?): String? = ni("getClientInfo")

    override fun getClientInfo(): Properties = ni("getClientInfo")

    override fun createArrayOf(typeName: String?, elements: Array<Any?>?): SqlArray =
        ni("createArrayOf")

    override fun createStruct(typeName: String?, attributes: Array<Any?>?): Struct =
        ni("createStruct")

    override fun setSchema(schema: String?): Unit = ni("setSchema")

    override fun getSchema(): String? = ni("getSchema")

    override fun abort(executor: Executor?): Unit = ni("abort")

    override fun setNetworkTimeout(executor: Executor?, milliseconds: Int): Unit =
        ni("setNetworkTimeout")

    override fun getNetworkTimeout(): Int = ni("getNetworkTimeout")

    override fun <T : Any?> unwrap(iface: Class<T>?): T = ni("unwrap")

    override fun isWrapperFor(iface: Class<*>?): Boolean = ni("isWrapperFor")
}
