package io.github.dravengarden.d1.jdbc

import java.sql.Connection
import java.sql.ResultSet
import java.sql.SQLFeatureNotSupportedException
import java.sql.SQLWarning
import java.sql.Statement

private fun ni(name: String): Nothing =
    throw SQLFeatureNotSupportedException("d1: Statement.$name not supported")

public abstract class AbstractStatement : Statement {
    override fun executeQuery(sql: String?): ResultSet = ni("executeQuery")

    override fun executeUpdate(sql: String?): Int = ni("executeUpdate")

    override fun executeUpdate(sql: String?, autoGeneratedKeys: Int): Int = ni("executeUpdate")

    override fun executeUpdate(sql: String?, columnIndexes: IntArray?): Int = ni("executeUpdate")

    override fun executeUpdate(sql: String?, columnNames: Array<String>?): Int = ni("executeUpdate")

    override fun execute(sql: String?): Boolean = ni("execute")

    override fun execute(sql: String?, autoGeneratedKeys: Int): Boolean = ni("execute")

    override fun execute(sql: String?, columnIndexes: IntArray?): Boolean = ni("execute")

    override fun execute(sql: String?, columnNames: Array<String>?): Boolean = ni("execute")

    override fun close(): Unit = ni("close")

    override fun getMaxFieldSize(): Int = ni("getMaxFieldSize")

    override fun setMaxFieldSize(max: Int): Unit = ni("setMaxFieldSize")

    override fun getMaxRows(): Int = ni("getMaxRows")

    override fun setMaxRows(max: Int): Unit = ni("setMaxRows")

    override fun setEscapeProcessing(enable: Boolean): Unit = ni("setEscapeProcessing")

    override fun getQueryTimeout(): Int = ni("getQueryTimeout")

    override fun setQueryTimeout(seconds: Int): Unit = ni("setQueryTimeout")

    override fun cancel(): Unit = ni("cancel")

    override fun getWarnings(): SQLWarning? = ni("getWarnings")

    override fun clearWarnings(): Unit = ni("clearWarnings")

    override fun setCursorName(name: String?): Unit = ni("setCursorName")

    override fun getResultSet(): ResultSet? = ni("getResultSet")

    override fun getUpdateCount(): Int = ni("getUpdateCount")

    override fun getMoreResults(): Boolean = ni("getMoreResults")

    override fun getMoreResults(current: Int): Boolean = ni("getMoreResults")

    override fun setFetchDirection(direction: Int): Unit = ni("setFetchDirection")

    override fun getFetchDirection(): Int = ni("getFetchDirection")

    override fun setFetchSize(rows: Int): Unit = ni("setFetchSize")

    override fun getFetchSize(): Int = ni("getFetchSize")

    override fun getResultSetConcurrency(): Int = ni("getResultSetConcurrency")

    override fun getResultSetType(): Int = ni("getResultSetType")

    override fun addBatch(sql: String?): Unit = ni("addBatch")

    override fun clearBatch(): Unit = ni("clearBatch")

    override fun executeBatch(): IntArray = ni("executeBatch")

    override fun getConnection(): Connection = ni("getConnection")

    override fun getGeneratedKeys(): ResultSet = ni("getGeneratedKeys")

    override fun getResultSetHoldability(): Int = ni("getResultSetHoldability")

    override fun isClosed(): Boolean = ni("isClosed")

    override fun setPoolable(poolable: Boolean): Unit = ni("setPoolable")

    override fun isPoolable(): Boolean = ni("isPoolable")

    override fun closeOnCompletion(): Unit = ni("closeOnCompletion")

    override fun isCloseOnCompletion(): Boolean = ni("isCloseOnCompletion")

    override fun getLargeUpdateCount(): Long = ni("getLargeUpdateCount")

    override fun setLargeMaxRows(max: Long): Unit = ni("setLargeMaxRows")

    override fun getLargeMaxRows(): Long = ni("getLargeMaxRows")

    override fun executeLargeBatch(): LongArray = ni("executeLargeBatch")

    override fun executeLargeUpdate(sql: String?): Long = ni("executeLargeUpdate")

    override fun executeLargeUpdate(sql: String?, autoGeneratedKeys: Int): Long = ni("executeLargeUpdate")

    override fun executeLargeUpdate(sql: String?, columnIndexes: IntArray?): Long = ni("executeLargeUpdate")

    override fun executeLargeUpdate(sql: String?, columnNames: Array<String>?): Long = ni("executeLargeUpdate")

    override fun <T : Any?> unwrap(iface: Class<T>?): T = ni("unwrap")

    override fun isWrapperFor(iface: Class<*>?): Boolean = ni("isWrapperFor")
}
