package io.github.dravengarden.d1.jdbc

import io.github.dravengarden.d1.core.D1Config
import io.github.dravengarden.d1.core.Wrangler
import io.github.dravengarden.d1.model.QueryResult
import java.sql.Connection
import java.sql.DatabaseMetaData
import java.sql.PreparedStatement
import java.sql.SQLException
import java.sql.SQLWarning
import java.sql.Statement

/**
 * A JDBC [Connection] over a single D1 database reached through the wrangler core.
 * There is no persistent socket — each statement spawns a `wrangler` invocation —
 * so "connecting" is just holding the parsed [D1Config] and confirming the backend
 * answers `SELECT 1`. The connection is read-oriented and always in autocommit:
 * wrangler runs each statement atomically and exposes no transaction control.
 */
public class D1Connection internal constructor(
    internal val config: D1Config,
    internal val wrangler: Wrangler,
) : AbstractConnection() {
    public constructor(config: D1Config) : this(config, Wrangler(config.toTransport(), config))

    private var closed = false
    private var autoCommit = true

    /**
     * Per-connection cache for schema-introspection queries. DataGrip issues the
     * same `sqlite_master` / `PRAGMA` reads dozens of times while building a tree,
     * and each is a ~1 s wrangler spawn; memoising them per connection makes a
     * sweep cheap. Cleared whenever a write runs, since DDL can change the schema.
     */
    private val introspectionCache = HashMap<String, QueryResult>()

    internal fun introspect(sql: String): QueryResult = introspectionCache.getOrPut(sql) { wrangler.execute(sql) }

    internal fun invalidateIntrospection() {
        introspectionCache.clear()
    }

    /** Run `SELECT 1` so a misconfigured URL / unreachable backend fails at connect. */
    internal fun checkConnectivity() {
        wrangler.execute("SELECT 1")
    }

    private fun require(sql: String?): String = sql ?: throw SQLException("sql is null")

    override fun createStatement(): Statement {
        ensureOpen()
        return D1Statement(this, wrangler)
    }

    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int): Statement = createStatement()

    override fun createStatement(
        resultSetType: Int,
        resultSetConcurrency: Int,
        resultSetHoldability: Int,
    ): Statement = createStatement()

    override fun prepareStatement(sql: String?): PreparedStatement {
        ensureOpen()
        return D1PreparedStatement(this, wrangler, require(sql))
    }

    override fun prepareStatement(
        sql: String?,
        resultSetType: Int,
        resultSetConcurrency: Int,
    ): PreparedStatement = prepareStatement(sql)

    override fun prepareStatement(
        sql: String?,
        resultSetType: Int,
        resultSetConcurrency: Int,
        resultSetHoldability: Int,
    ): PreparedStatement = prepareStatement(sql)

    override fun prepareStatement(sql: String?, autoGeneratedKeys: Int): PreparedStatement = prepareStatement(sql)

    override fun prepareStatement(sql: String?, columnIndexes: IntArray?): PreparedStatement = prepareStatement(sql)

    override fun prepareStatement(sql: String?, columnNames: Array<String>?): PreparedStatement = prepareStatement(sql)

    override fun getMetaData(): DatabaseMetaData = D1DatabaseMetaData(this)

    override fun isValid(timeout: Int): Boolean =
        if (closed) {
            false
        } else {
            try {
                checkConnectivity()
                true
            } catch (_: Exception) {
                false
            }
        }

    private fun ensureOpen() {
        if (closed) throw SQLException("connection is closed")
    }

    override fun nativeSQL(sql: String?): String = sql ?: ""

    override fun setAutoCommit(autoCommit: Boolean) {
        this.autoCommit = autoCommit
    }

    override fun getAutoCommit(): Boolean = autoCommit

    override fun commit() {
        // Each wrangler invocation is atomic; there is no open transaction to commit.
    }

    override fun rollback() {
        throw SQLException("d1 has no transaction control (autocommit only)")
    }

    override fun close() {
        closed = true
    }

    override fun isClosed(): Boolean = closed

    override fun setReadOnly(readOnly: Boolean) {
        // Accepted but not enforced — writes are simply not implemented yet.
    }

    override fun isReadOnly(): Boolean = false

    override fun setCatalog(catalog: String?) {
        // D1 has no catalog concept.
    }

    override fun getCatalog(): String? = null

    override fun setSchema(schema: String?) {
        // D1 has no schema concept.
    }

    override fun getSchema(): String? = null

    override fun setTransactionIsolation(level: Int) {
        // Only TRANSACTION_NONE is meaningful.
    }

    override fun getTransactionIsolation(): Int = Connection.TRANSACTION_NONE

    override fun getWarnings(): SQLWarning? = null

    override fun clearWarnings() {
        // No warnings are accumulated.
    }

    override fun setHoldability(holdability: Int) {
        // Single holdability; ignore.
    }

    override fun getHoldability(): Int = java.sql.ResultSet.CLOSE_CURSORS_AT_COMMIT

    override fun getTypeMap(): MutableMap<String, Class<*>> = mutableMapOf()

    override fun getNetworkTimeout(): Int = 0
}
